
POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nome": "ES",
  "descricao": "dsdsddfsdfds",
  "cnpj": "2324234234",
  "email": "sadsadsa@gmail.com"
}

###

GET  http://localhost:8080/empresas

###

GET  http://localhost:8080/empresas/1

###

DELETE  http://localhost:8080/empresas/1


###


PUT  http://localhost:8080/empresas/1
Content-Type: application/json

{
  "nome": "ESSSADS",
  "descricao": "dsdsddfsDSADSADSADSAdfds",
  "cnpj": "232423232434234",
  "email": "saDSFDDSFSDFDSdsadsa@gmail.com"
}

###

POST http://localhost:8080/empresas/1/criarVaga
Content-Type: application/json

{
 "cargo": "Algum Cargo",
  "descricao": "Alguma Descrição",
  "contratacao": "Alguma Contracao",
  "remuneracao": 1200
}

###

POST  http://localhost:8080/candidatos
Content-Type: application/json

{
  "nome": "Zé de Tal",
  "email": "ze@example.com",
  "telefone": "987654321",
  "enderecos": [
    {
      "rua": "Rua Nova",
      "cidade": "Cidade Nova",
      "estado": "Estado Novo",
      "tipo": "Comercial",
      "uf": "CN"
    }
  ]
}


###

POST http://localhost:8080/candidaturas/candidatar/1/1
Content-Type: application/json

{
  "mensagem": "aa"

}
###


GET http://localhost:8080/candidatos/1

###
